//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boleto2Net {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Html {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Html() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boleto2Net.Html", typeof(Html).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barra {
            get {
                object obj = ResourceManager.GetObject("barra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barrainterna {
            get {
                object obj = ResourceManager.GetObject("barrainterna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///			&lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;rBb&quot;&gt;
        ///						&lt;td class=&quot;Ac ld&quot; colspan=&quot;4&quot;&gt;Demonstrativo&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;ct&quot;&gt;
        ///					&lt;td class=&quot;w62&quot;&gt;&lt;/td&gt;
        ///					&lt;td class=&quot;w62&quot;&gt;&lt;/td&gt;
        ///					&lt;td class=&quot;w62&quot;&gt;&lt;/td&gt;
        ///					&lt;td class=&quot;w62&quot;&gt;&lt;/td&gt;				
        ///					@ITENSDEMONSTRATIVO
        ///			&lt;/tr&gt;							
        ///		&lt;/table class=&quot;rBb td&quot;&gt;	
        ///		&lt;table class=&quot;ctN w666&quot;&gt;
        ///				&lt;tr class=&quot;h13&quot;&gt;&lt;td /&gt;&lt;/tr&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;Ar&quot;&gt;Corte na linha pontilhada&lt;/td&gt;&lt;/tr&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;cut&quot; /&gt;&lt;/tr&gt;
        ///		&lt;/table&gt;				
        ///		.
        /// </summary>
        internal static string CabecalhoTabelaDemonstrativo {
            get {
                return ResourceManager.GetString("CabecalhoTabelaDemonstrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///						&lt;tr&gt;
        ///								&lt;td valign=&quot;top&quot;&gt;
        ///										&lt;table class=&quot;w150 mt23&quot;&gt;
        ///												&lt;tr class=&quot;ct cpN BHead&quot;&gt;
        ///														&lt;td class=&quot;ld&quot;&gt;
        ///																Recibo do Pagador
        ///														&lt;/td&gt;
        ///												&lt;/tr&gt;
        ///										&lt;/table&gt;
        ///										&lt;table class=&quot;w150&quot;&gt;
        ///												&lt;tr class=&quot;ct h13 At&quot;&gt;
        ///														&lt;td class=&quot;w298&quot;&gt;
        ///																Beneficiário
        ///														&lt;/td&gt;
        ///												&lt;/tr&gt;
        ///												&lt;tr class=&quot;cp h12 At rBb&quot;&gt;
        ///														&lt;td&gt;        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Carne {
            get {
                return ResourceManager.GetString("Carne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;cpN BT1 Ar&quot;&gt;Comprovante de Entrega&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega1 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;BHead&quot;&gt;
        ///						&lt;td class=&quot;imgLogo Al&quot;&gt;&lt;img src=&quot;@URLIMAGEMLOGO&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w65 Ab bc Ac&quot;&gt;@CODIGOBANCO-@DIGITOBANCO&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w500 Ar ld&quot; valign=&quot;bottom&quot;&gt;Comprovante de Entrega&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega2 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w298&quot;&gt;Beneficiário&lt;/td&gt;
        ///						&lt;td class=&quot;w126&quot;&gt;Agência / Código do Beneficiário&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Vencimento&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Nº do Documento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@CEDENTE&lt;/td&gt;
        ///						&lt;td&gt;@AGENCIACODIGOCEDENTE&lt;/td&gt;
        ///						&lt;td&gt;@DATAVENCIMENTO&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@NUMERODOCUMENTO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega3 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w298&quot;&gt;Pagador&lt;/td&gt;
        ///						&lt;td class=&quot;w126&quot;&gt;Carteira / Nosso Número&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Espécie&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Valor do Documento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@SACADO&lt;/td&gt;
        ///						&lt;td&gt;@NOSSONUMERO&lt;/td&gt;
        ///						&lt;td&gt;@ESPECIE&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@=VALORDOCUMENTO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega4 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w544&quot;&gt;Local de pagamento&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Data de Processamento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@LOCALPAGAMENTO&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@DATAPROCESSAMENTO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega5 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w150&quot;&gt;Recebi(emos) o bloqueto&lt;/td&gt;
        ///						&lt;td class=&quot;w104&quot;&gt;Data&lt;/td&gt;
        ///						&lt;td class=&quot;w164&quot;&gt;Assinatura&lt;/td&gt;
        ///						&lt;td class=&quot;w105&quot;&gt;Data&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Entregador&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td /&gt;
        ///						&lt;td /&gt;
        ///						&lt;td /&gt;
        ///						&lt;td /&gt;
        ///						&lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega6 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ctN&quot;&gt;
        ///						&lt;td class=&quot;w666 pL6&quot;&gt;Motivo de não entrega (para uso da empresa entregadora)&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr&gt;
        ///						&lt;td&gt;
        ///								&lt;table class=&quot;cpN w666&quot;&gt;
        ///										&lt;tr&gt;
        ///												&lt;td class=&quot;w104 pL6&quot;&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp;Mudou-se&lt;/td&gt;
        ///												&lt;td class=&quot;w104&quot;&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp;Ausente&lt;/td&gt;
        ///												&lt;td&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp;Não existe n. indicado&lt;/td&gt;
        ///												&lt;td&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp;Recusado&lt;/td&gt;
        ///												&lt;td class=&quot;w104&quot;&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ComprovanteEntrega7 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///	 &lt;tr class=&quot;ctN&quot;&gt;
        ///			&lt;td class=&quot;w666 pL6&quot;&gt;Observações (para uso da empresa entregadora)&lt;/td&gt;
        ///	 &lt;/tr&gt;
        ///	 &lt;tr&gt;
        ///			&lt;td&gt;
        ///				 &lt;table class=&quot;cpN w666&quot;&gt;
        ///						&lt;tr&gt;
        ///							 &lt;td class=&quot;w104 pL6&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td class=&quot;w104&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td class=&quot;w104&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///						&lt;/tr&gt;
        ///						&lt;tr&gt;
        ///							 &lt;td class=&quot;pL6&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/ [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ComprovanteEntrega71 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corte {
            get {
                object obj = ResourceManager.GetObject("corte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;div class=&quot;cut w792 txtRight ct&quot;&gt;Corte na linha pontilhada&lt;/div&gt;.
        /// </summary>
        internal static string CorteLinha {
            get {
                return ResourceManager.GetString("CorteLinha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///				&lt;tr class=&quot;ct&quot;&gt;
        ///					&lt;td class=&quot;cp&quot;&gt;@DESCRICAOGRUPO&lt;/td&gt;
        ///					&lt;td&gt;@DESCRICAOITEM&lt;/td&gt;
        ///					&lt;td&gt;@REFERENCIAITEM&lt;/td&gt;
        ///					&lt;td&gt;@VALORITEM&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		.
        /// </summary>
        internal static string GrupoDemonstrativo {
            get {
                return ResourceManager.GetString("GrupoDemonstrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;cpN&quot;&gt;
        ///						&lt;td class=&quot;At Ac&quot;&gt;@TITULO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;ti&quot;&gt;
        ///						&lt;td class=&quot;At Ac&quot;&gt;@INSTRUCAO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string Instrucoes {
            get {
                return ResourceManager.GetString("Instrucoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ponto {
            get {
                object obj = ResourceManager.GetObject("ponto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte01 --&gt;
        ///&lt;table class=&quot;w792 bold header&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;barRight w165  vMiddle&quot;&gt;&lt;img class=&quot;logo&quot; src=&quot;@URLIMAGEMLOGO&quot; /&gt;&lt;/td&gt;
        ///        &lt;td class=&quot;barRight w66 codeBank txtCenter vMiddle&quot;&gt;@CODIGOBANCO-@DIGITOBANCO&lt;/td&gt;
        ///        &lt;td class=&quot;txtRight vBottom&quot;&gt;@LINHADIGITAVEL&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte01 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte02 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Local de Pagamento&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@LOCALPAGAMENTO&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;w198&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Vencimento&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12 txtRight&quot;&gt;@DATAVENCIMENTO&lt;/div&gt;
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte02 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte03 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Beneficiário&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@CEDENTE_BOLETO&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;w198&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Agência/Código Beneficiário&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12 txtRight&quot;&gt;@AGENCIACONTA&lt;/div&gt;
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte03 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte04 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;w132 barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Data do Documento&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@DATADOCUMENTO&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;w165 barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Nº do Documento&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@NUMERODOCUMENTO&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;w99 barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Espécie do Doc&lt;/div&gt;
        ///          [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ReciboCedenteParte04 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte05 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;w132 barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Uso do Banco&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;&amp;nbsp;&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;w66 barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;C I P&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;&amp;nbsp;&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;w66 barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Carteira&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@CARTEIRA&lt;/div&gt;
        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ReciboCedenteParte05 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte06 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;w594&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Instruções (Texto de responsabilidade do beneficiário)&lt;/div&gt;
        ///            &lt;div class=&quot;cp&quot;&gt;@INSTRUCOES&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;w198 barLeft&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;(-) Desconto/Abatimentos&lt;/div&gt;
        ///            &lt;div class=&quot;cp barBottom h12 txtRight&quot;&gt;@DESCONTOS&lt;/div&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;(-) Outras Deduções&lt;/div&gt;
        ///             [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ReciboCedenteParte06 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte07 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Pagador&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;
        ///                @SACADO&lt;br&gt;
        ///                @ENDERECOSACADO
        ///            &lt;/div&gt;
        ///        &lt;/td&gt;
        ///
        ///        &lt;td class=&quot;w198 vBottom&quot;&gt;
        ///            &lt;div class=&quot;barLeft ct h11&quot;&gt;Cód. de Baixa&lt;/div&gt;
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte07 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte08 --&gt;
        ///&lt;table class=&quot;w792&quot;&gt;
        ///    &lt;tr class=&quot;ct h13&quot;&gt;
        ///        &lt;td class=&quot;&quot;&gt;Sacador/Avalista: &lt;b class=&quot;cp&quot;&gt;@AVALISTA&lt;/b&gt;&lt;/td&gt;
        ///        &lt;td class=&quot;w297 txtRight&quot;&gt;Autenticação mecânica - &lt;b&gt;Ficha de Compensação&lt;/b&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte08 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboCedenteParte09 --&gt;
        ///&lt;div class=&quot;w792 codeBar&quot;&gt;
        ///    @IMAGEMCODIGOBARRA
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ReciboCedenteParte09 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///			&lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;BHead BT2&quot;&gt;
        ///						&lt;td class=&quot;imgLogo Al&quot;&gt;&lt;img src=&quot;@URLIMAGEMLOGO&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w65 Ab bc Ac&quot;&gt;@CODIGOBANCO-@DIGITOBANCO&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w500 Ar ld&quot; valign=&quot;bottom&quot;&gt;RECIBO DO SACADO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///			&lt;/table&gt;				
        ///			&lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td&gt;Local de pagamento&lt;/td&gt;
        ///						&lt;td&gt;&lt;/td&gt;
        ///				&lt;/tr&gt;			 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ReciboCedenteRelatorioValores {
            get {
                return ResourceManager.GetString("ReciboCedenteRelatorioValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboSacadoParte01 --&gt;
        ///&lt;table class=&quot;w792 bold header&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;barRight w165  vMiddle&quot;&gt;&lt;img class=&quot;logo&quot; src=&quot;@URLIMAGEMLOGO&quot; /&gt;&lt;/td&gt;
        ///        &lt;td class=&quot;barRight w66 codeBank txtCenter vMiddle&quot;&gt;@CODIGOBANCO-@DIGITOBANCO&lt;/td&gt;
        ///        &lt;td class=&quot;txtRight vBottom&quot;&gt;@LINHADIGITAVEL&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte01 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboSacadoParte02 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;w330 barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Beneficiário&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@CEDENTE&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;barRight w132&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Agência/Código do Beneficiário&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@AGENCIACODIGOCEDENTE&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Espécie&lt;/div&gt;
        ///             [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ReciboSacadoParte02 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboSacadoParte03 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Beneficiário Endereço/Sacador Avalista&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@ENDERECOCEDENTE&lt;/div&gt;
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte03 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboSacadoParte04 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///
        ///        &lt;td class=&quot;barRight w198&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Número do documento&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@NUMERODOCUMENTO&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;CPF/CNPJ&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;@CPFCNPJ&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;barRight w198&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Vencimento&lt;/div&gt;
        ///            &lt;div class=&quot;cp  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ReciboSacadoParte04 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboSacadoParte05 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///
        ///        &lt;td class=&quot;barRight w198&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;(-) Desconto/Abatimentos&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12 txtRight&quot;&gt;@DESCONTOS&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;barRight w132&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;(-) Outras Deduções&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12 txtRight&quot;&gt;@OUTRASDEDUCOES&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;barRight&quot;&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;(+) Mora/M [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ReciboSacadoParte05 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboSacadoParte06 --&gt;
        ///&lt;table class=&quot;w792 barRight barLeft barBottom&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td&gt;
        ///            &lt;div class=&quot;ct h11&quot;&gt;Pagador&lt;/div&gt;
        ///            &lt;div class=&quot;cp h12&quot;&gt;
        ///                @SACADO&lt;br&gt;
        ///                @ENDERECOSACADO
        ///            &lt;/div&gt;
        ///        &lt;/td&gt;
        ///
        ///        &lt;td class=&quot;w198 vBottom&quot;&gt;
        ///            &lt;div class=&quot;barLeft ct h11&quot;&gt;Cód. de Baixa&lt;/div&gt;
        ///        &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte06 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!-- ReciboSacadoParte07 --&gt;
        ///&lt;table class=&quot;w792&quot;&gt;
        ///    &lt;tr class=&quot;ct h13&quot;&gt;
        ///        &lt;td class=&quot;&quot;&gt;
        ///            &lt;div class=&quot;h11&quot;&gt;Instruções&lt;/div&gt;
        ///            &lt;div class=&quot;h13&quot;&gt;@INSTRUCOES&lt;/div&gt;
        ///        &lt;/td&gt;
        ///        &lt;td class=&quot;w192 txtRight&quot;&gt;Autenticação mecânica&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte07 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 
        ///				&lt;tr class=&quot;cp h13 rBb&quot;&gt;
        ///					&lt;td&gt;Total&lt;/td&gt;
        ///					&lt;td&gt;&lt;/td&gt;
        ///					&lt;td&gt;&lt;/td&gt;
        ///					&lt;td&gt;@VALORTOTALGRUPO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		.
        /// </summary>
        internal static string TotalDemonstrativo {
            get {
                return ResourceManager.GetString("TotalDemonstrativo", resourceCulture);
            }
        }
    }
}
